[build]
builder = "dockerfile"
# 默认使用完整依赖的Dockerfile
dockerfilePath = "Dockerfile"
# 生产环境推荐使用: dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.environment]
PORT = "8000"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

# 监听后端目录变化
[deploy.watch]
paths = ["**"]

# 构建时忽略某些文件
[build.watch]
ignore = [
    "**/*.md",
    "**/test_*.py",
    "**/*_test.py",
    "**/tests/",
    "**/__pycache__/",
    "**/.pytest_cache/",
    "**/data/",
    "**/migrations/"
]