[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "python backup_critical_data.py && python consolidate_migrations.py consolidate && python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.environment]
PORT = "8000"
DEBUG = "false"
WORKERS = "1"
APP_ENV = "prod"

# 添加数据卷配置
[[deploy.volumes]]
source = "database"
target = "/app/data"

