[build]
builder = "dockerfile"
dockerfilePath = "personal_finance_flutter/Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.environment]
PORT = "80"
