"""add wise_exchange_rates table

Revision ID: 4d412d44dc3e
Revises: 9b2fcf59ac80
Create Date: 2025-07-06 23:06:18.661163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d412d44dc3e'
down_revision: Union[str, Sequence[str], None] = '9b2fcf59ac80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
