"""add_nav_field_to_user_operations

Revision ID: 843fdae84b37
Revises: a75b8ab8d7ec
Create Date: 2025-07-03 10:06:23.279341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843fdae84b37'
down_revision: Union[str, Sequence[str], None] = 'a75b8ab8d7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_operations', sa.Column('nav', sa.DECIMAL(precision=15, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_operations', 'nav')
    # ### end Alembic commands ###
