"""add_nav_field_to_user_operations

Revision ID: 849be9e8b559
Revises: a75b8ab8d7ec
Create Date: 2025-07-03 10:05:59.628369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849be9e8b559'
down_revision: Union[str, Sequence[str], None] = 'a75b8ab8d7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
