"""fix_okx_market_data_precision

Revision ID: 9ab46480ba00
Revises: c56f9f034ac1
Create Date: 2025-07-17 16:03:10.267878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '9ab46480ba00'
down_revision: Union[str, Sequence[str], None] = 'c56f9f034ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DROP INDEX IF EXISTS idx_okx_balances_account"))
    op.execute(text("DROP INDEX IF EXISTS idx_okx_balances_currency"))
    op.alter_column('okx_market_data', 'last_price',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('okx_market_data', 'bid_price',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'ask_price',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'high_24h',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'low_24h',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'volume_24h',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'change_24h',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'change_rate_24h',
               existing_type=sa.DECIMAL(precision=15, scale=8),
               type_=sa.DECIMAL(precision=20, scale=8),
               existing_nullable=True)
    op.execute(text("DROP INDEX IF EXISTS idx_okx_positions_account"))
    op.execute(text("DROP INDEX IF EXISTS idx_okx_positions_timestamp"))
    op.execute(text("DROP INDEX IF EXISTS idx_okx_transactions_account"))
    op.execute(text("DROP INDEX IF EXISTS idx_okx_transactions_timestamp"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_okx_transactions_timestamp'), 'okx_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('idx_okx_transactions_account'), 'okx_transactions', ['account_id'], unique=False)
    op.create_index(op.f('idx_okx_positions_timestamp'), 'okx_positions', ['timestamp'], unique=False)
    op.create_index(op.f('idx_okx_positions_account'), 'okx_positions', ['account_id'], unique=False)
    op.alter_column('okx_market_data', 'change_rate_24h',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'change_24h',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'volume_24h',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'low_24h',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'high_24h',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'ask_price',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'bid_price',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=True)
    op.alter_column('okx_market_data', 'last_price',
               existing_type=sa.DECIMAL(precision=20, scale=8),
               type_=sa.DECIMAL(precision=15, scale=8),
               existing_nullable=False)
    op.create_index(op.f('idx_okx_balances_currency'), 'okx_balances', ['currency'], unique=False)
    op.create_index(op.f('idx_okx_balances_account'), 'okx_balances', ['account_id'], unique=False)
    # ### end Alembic commands ###
