"""add_wise_transactions_and_balances_tables

Revision ID: 9b2fcf59ac80
Revises: f9adc45cf4ec
Create Date: 2025-07-06 22:27:45.713024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b2fcf59ac80'
down_revision: Union[str, Sequence[str], None] = 'f9adc45cf4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
