"""add_exclude_dates_to_dca_plans

Revision ID: f9adc45cf4ec
Revises: 04f8249fc418
Create Date: 2025-07-04 15:04:24.348735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9adc45cf4ec'
down_revision: Union[str, Sequence[str], None] = '04f8249fc418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dca_plans', sa.Column('exclude_dates', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dca_plans', 'exclude_dates')
    # ### end Alembic commands ###
