[phases.setup]
nixPkgs = ["flutter"]

[phases.install]
cmds = ["flutter pub get"]

[phases.build]
cmds = ["flutter build web --release --no-tree-shake-icons"]

[start]
cmd = "cd build/web && python3 -m http.server $PORT"
