name: personal_finance_flutter
description: "多资产投资记录与收益分析系统 Flutter版"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 状态管理
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP客户端和网络
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # UI组件
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296

  # 图表
  fl_chart: ^0.66.2

  # 工具类
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # 导航
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # 代码生成
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true