"""add_okx_account_overview_table

Revision ID: 033880ebf93b
Revises: 9ab46480ba00
Create Date: 2025-07-18 11:23:38.090641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '033880ebf93b'
down_revision: Union[str, Sequence[str], None] = '9ab46480ba00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('okx_account_overview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_total_usd', sa.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('funding_total_usd', sa.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('savings_total_usd', sa.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('total_assets_usd', sa.DECIMAL(precision=15, scale=8), nullable=False),
    sa.Column('total_currencies', sa.Integer(), nullable=False),
    sa.Column('trading_currencies_count', sa.Integer(), nullable=False),
    sa.Column('funding_currencies_count', sa.Integer(), nullable=False),
    sa.Column('savings_currencies_count', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(text("DROP INDEX IF EXISTS ix_okx_account_overview_id"))
    op.create_index(op.f('ix_okx_account_overview_id'), 'okx_account_overview', ['id'], unique=False)
    op.execute(text("DROP INDEX IF EXISTS ix_okx_account_overview_last_update"))
    op.create_index(op.f('ix_okx_account_overview_last_update'), 'okx_account_overview', ['last_update'], unique=False)
    op.drop_index(op.f('idx_okx_market_data_inst_id'), table_name='okx_market_data')
    op.drop_index(op.f('idx_okx_market_data_timestamp'), table_name='okx_market_data')
    op.drop_constraint(op.f('uq_okx_market_data'), 'okx_market_data', type_='unique')
    op.create_unique_constraint('uq_okx_market_data', 'okx_market_data', ['inst_id', 'inst_type', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_okx_market_data', 'okx_market_data', type_='unique')
    op.create_unique_constraint(op.f('uq_okx_market_data'), 'okx_market_data', ['inst_id', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_okx_market_data_timestamp'), 'okx_market_data', ['timestamp'], unique=False)
    op.create_index(op.f('idx_okx_market_data_inst_id'), 'okx_market_data', ['inst_id'], unique=False)
    op.drop_index(op.f('ix_okx_account_overview_last_update'), table_name='okx_account_overview')
    op.drop_index(op.f('ix_okx_account_overview_id'), table_name='okx_account_overview')
    op.drop_table('okx_account_overview')
    # ### end Alembic commands ###
