"""add_fee_rate_to_dca_plans

Revision ID: 04f8249fc418
Revises: c6ea9ed77ea8
Create Date: 2025-07-04 00:34:20.523580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f8249fc418'
down_revision: Union[str, Sequence[str], None] = 'c6ea9ed77ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dca_plans', sa.Column('fee_rate', sa.DECIMAL(precision=5, scale=4), nullable=True))
    # 注意：SQLite不支持外键约束修改，外键关系已在模型中定义
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dca_plans', 'fee_rate')
    # ### end Alembic commands ###
