"""add wise primary/secondary amount fields

Revision ID: ff5423642f10
Revises: 8a343c129269
Create Date: 2025-07-22 15:39:48.674554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5423642f10'
down_revision: Union[str, Sequence[str], None] = '8a343c129269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wise_transactions', sa.Column('primary_amount_value', sa.DECIMAL(precision=15, scale=4), nullable=True))
    op.add_column('wise_transactions', sa.Column('primary_amount_currency', sa.String(length=10), nullable=True))
    op.add_column('wise_transactions', sa.Column('secondary_amount_value', sa.DECIMAL(precision=15, scale=4), nullable=True))
    op.add_column('wise_transactions', sa.Column('secondary_amount_currency', sa.String(length=10), nullable=True))
    # 只在本次迁移时清空wise_transactions表（PostgreSQL专用）
    from sqlalchemy import text
    op.execute(text("TRUNCATE TABLE wise_transactions RESTART IDENTITY CASCADE;"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wise_transactions', 'secondary_amount_currency')
    op.drop_column('wise_transactions', 'secondary_amount_value')
    op.drop_column('wise_transactions', 'primary_amount_currency')
    op.drop_column('wise_transactions', 'primary_amount_value')
    # ### end Alembic commands ###
